-- ================================================================
-- English Talking Coach — Initial Schema
-- Migration: 20260422000000
-- ================================================================

-- ----------------------------------------------------------------
-- EXTENSIONS
-- ----------------------------------------------------------------

create extension if not exists "pgcrypto";

-- ----------------------------------------------------------------
-- ENUMS
-- ----------------------------------------------------------------

create type public.difficulty_level as enum (
  'beginner',
  'intermediate',
  'advanced'
);

create type public.session_status as enum (
  'in_progress',
  'completed',
  'abandoned'
);

-- ================================================================
-- TABLES
-- ================================================================

-- ----------------------------------------------------------------
-- 1. users
--    Profile table that extends auth.users (1-to-1).
--    Created automatically via trigger on first sign-up.
-- ----------------------------------------------------------------

create table public.users (
  id            uuid        primary key references auth.users(id) on delete cascade,
  email         text        not null,
  display_name  text,
  avatar_url    text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

comment on table public.users is 'Public user profiles extending auth.users.';

-- ----------------------------------------------------------------
-- 2. scenes
--    Preset and user-created conversation scenarios.
--    is_system = true rows are seeded by migrations only.
-- ----------------------------------------------------------------

create table public.scenes (
  id               uuid             primary key default gen_random_uuid(),
  name             text             not null,
  description      text             not null,
  -- Full system prompt for the AI role in this scenario
  ai_role_prompt   text             not null,
  difficulty       difficulty_level not null,
  -- e.g. ARRAY['negotiation', 'formal vocabulary']
  training_focus   text[]           not null default '{}',
  is_system        boolean          not null default false,
  -- null for system scenes; set to user id for custom scenes
  created_by       uuid             references public.users(id) on delete set null,
  created_at       timestamptz      not null default now()
);

comment on table  public.scenes is 'Preset and user-custom conversation scenarios.';
comment on column public.scenes.ai_role_prompt is 'System prompt injected as the AI persona for this scene.';

-- ----------------------------------------------------------------
-- 3. sessions
--    One row per conversation attempt.
--    transcript stores the full message history as a JSONB array:
--      [{ "role": "user"|"assistant", "content": "...", "ts": "<iso>" }]
-- ----------------------------------------------------------------

create table public.sessions (
  id                       uuid           primary key default gen_random_uuid(),
  user_id                  uuid           not null references public.users(id) on delete cascade,
  -- null when using a fully custom (ad-hoc) scene
  scene_id                 uuid           references public.scenes(id) on delete set null,
  -- filled only when scene_id is null (user-described custom scenario)
  custom_scene_description text,
  status                   session_status not null default 'in_progress',
  -- populated when session ends
  duration_seconds         integer        check (duration_seconds >= 0),
  transcript               jsonb          not null default '[]'::jsonb,
  started_at               timestamptz    not null default now(),
  ended_at                 timestamptz,
  created_at               timestamptz    not null default now(),

  constraint session_has_scene check (
    scene_id is not null or custom_scene_description is not null
  )
);

comment on table  public.sessions   is 'One record per voice conversation attempt.';
comment on column public.sessions.transcript is
  'Array of {role, content, ts} objects. Appended in real-time during the session.';

-- ----------------------------------------------------------------
-- 4. reports
--    One-to-one with sessions; generated by the backend after
--    a session completes.
--
--    pronunciation_feedback JSONB shape:
--      [{ "phoneme": "th", "count": 3, "examples": ["the", "that"] }]
--
--    grammar_errors JSONB shape:
--      [{ "original": "I have went", "correction": "I have gone",
--         "rule": "past participle", "severity": "high"|"medium"|"low" }]
-- ----------------------------------------------------------------

create table public.reports (
  id                     uuid        primary key default gen_random_uuid(),
  session_id             uuid        not null unique references public.sessions(id) on delete cascade,
  user_id                uuid        not null references public.users(id)   on delete cascade,

  -- Component scores (0–100)
  pronunciation_score    numeric(5,2) check (pronunciation_score    between 0 and 100),
  grammar_score          numeric(5,2) check (grammar_score          between 0 and 100),
  fluency_score          numeric(5,2) check (fluency_score          between 0 and 100),
  vocabulary_score       numeric(5,2) check (vocabulary_score       between 0 and 100),
  performance_score      numeric(5,2) check (performance_score      between 0 and 100),
  -- Weighted aggregate of the above
  overall_score          numeric(5,2) check (overall_score          between 0 and 100),

  pronunciation_feedback jsonb        not null default '[]'::jsonb,
  grammar_errors         jsonb        not null default '[]'::jsonb,

  strengths              text[]       not null default '{}',
  suggestions            text[]       not null default '{}',

  created_at             timestamptz  not null default now()
);

comment on table public.reports is 'AI-generated analysis report for a completed session.';

-- ----------------------------------------------------------------
-- 5. weakness_profile
--    One row per user; upserted by the backend after each report.
--
--    pronunciation_weaknesses JSONB shape:
--      [{ "phoneme": "th", "error_count": 12,
--         "examples": ["this","think"], "last_seen": "<iso>" }]
--
--    grammar_weaknesses JSONB shape:
--      [{ "pattern": "present perfect vs simple past", "error_count": 7,
--         "examples": ["I have went"], "last_seen": "<iso>" }]
--
--    vocabulary_gaps JSONB shape:
--      [{ "category": "business idioms", "gap_count": 4,
--         "suggested_words": ["leverage","synergy"], "last_seen": "<iso>" }]
-- ----------------------------------------------------------------

create table public.weakness_profile (
  id                       uuid        primary key default gen_random_uuid(),
  user_id                  uuid        not null unique references public.users(id) on delete cascade,
  pronunciation_weaknesses jsonb       not null default '[]'::jsonb,
  grammar_weaknesses       jsonb       not null default '[]'::jsonb,
  vocabulary_gaps          jsonb       not null default '[]'::jsonb,
  total_sessions           integer     not null default 0 check (total_sessions >= 0),
  updated_at               timestamptz not null default now()
);

comment on table public.weakness_profile is
  'Aggregated weakness profile for a user, rebuilt after each session report.';

-- ================================================================
-- INDEXES
-- ================================================================

-- sessions -------------------------------------------------------
-- Primary access pattern: fetch all sessions for a user, newest first
create index idx_sessions_user_started
  on public.sessions(user_id, started_at desc);

create index idx_sessions_scene_id
  on public.sessions(scene_id);

create index idx_sessions_status
  on public.sessions(status)
  where status = 'in_progress';           -- partial: only live sessions

-- reports --------------------------------------------------------
create index idx_reports_user_id
  on public.reports(user_id);

-- session_id is already covered by the unique constraint index.

-- scenes ---------------------------------------------------------
create index idx_scenes_difficulty
  on public.scenes(difficulty);

create index idx_scenes_created_by
  on public.scenes(created_by)
  where created_by is not null;           -- partial: skip system scenes

-- ================================================================
-- FUNCTIONS & TRIGGERS
-- ================================================================

-- ----------------------------------------------------------------
-- Reusable updated_at stamper
-- ----------------------------------------------------------------

create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_users_updated_at
  before update on public.users
  for each row execute function public.handle_updated_at();

create trigger trg_weakness_profile_updated_at
  before update on public.weakness_profile
  for each row execute function public.handle_updated_at();

-- ----------------------------------------------------------------
-- Auto-provision user profile + weakness_profile on first sign-up.
-- security definer so the trigger can bypass RLS.
-- ----------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;

  insert into public.weakness_profile (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

create trigger trg_on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ================================================================
-- ROW LEVEL SECURITY
-- ================================================================

alter table public.users            enable row level security;
alter table public.scenes           enable row level security;
alter table public.sessions         enable row level security;
alter table public.reports          enable row level security;
alter table public.weakness_profile enable row level security;

-- ----------------------------------------------------------------
-- users
-- ----------------------------------------------------------------

-- The trigger (security definer) handles INSERT; no client INSERT policy needed.

create policy "users: select own"
  on public.users for select
  using (auth.uid() = id);

create policy "users: update own"
  on public.users for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- ----------------------------------------------------------------
-- scenes
-- ----------------------------------------------------------------

-- Any visitor (including anon) can browse system scenes (landing page use-case)
create policy "scenes: anyone reads system scenes"
  on public.scenes for select
  using (is_system = true);

-- Authenticated users can also read their own custom scenes
create policy "scenes: owner reads own custom scenes"
  on public.scenes for select
  to authenticated
  using (auth.uid() = created_by);

-- Authenticated users may create custom (non-system) scenes
create policy "scenes: owner inserts custom scenes"
  on public.scenes for insert
  to authenticated
  with check (
    auth.uid() = created_by
    and is_system = false
  );

create policy "scenes: owner updates own custom scenes"
  on public.scenes for update
  to authenticated
  using  (auth.uid() = created_by and is_system = false)
  with check (auth.uid() = created_by and is_system = false);

create policy "scenes: owner deletes own custom scenes"
  on public.scenes for delete
  to authenticated
  using (auth.uid() = created_by and is_system = false);

-- ----------------------------------------------------------------
-- sessions
-- ----------------------------------------------------------------

create policy "sessions: select own"
  on public.sessions for select
  using (auth.uid() = user_id);

create policy "sessions: insert own"
  on public.sessions for insert
  with check (auth.uid() = user_id);

-- Allow the client to update transcript / status / ended_at in real-time
create policy "sessions: update own"
  on public.sessions for update
  using  (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "sessions: delete own"
  on public.sessions for delete
  using (auth.uid() = user_id);

-- ----------------------------------------------------------------
-- reports
-- ----------------------------------------------------------------

-- Reports are written exclusively by the backend (service role key).
-- The client only reads.

create policy "reports: select own"
  on public.reports for select
  using (auth.uid() = user_id);

-- ----------------------------------------------------------------
-- weakness_profile
-- ----------------------------------------------------------------

-- Updated exclusively by the backend (service role key).
-- The client only reads.

create policy "weakness_profile: select own"
  on public.weakness_profile for select
  using (auth.uid() = user_id);

-- ================================================================
-- SEED DATA: PRESET SCENES
-- ================================================================

insert into public.scenes
  (name, description, ai_role_prompt, difficulty, training_focus, is_system)
values

-- 1 全英辩论 --------------------------------------------------------
(
  '全英辩论',
  '与 AI 就争议性话题展开全英文正式辩论，锻炼逻辑论证和即兴反驳能力。',
  'You are a rigorous formal debate opponent. The user will state a position on a controversial topic; you argue the opposing side with logic, evidence, and rhetorical skill.

Rules:
- Use formal debate register (moreover, nevertheless, one must concede, etc.).
- Challenge every weak or unsupported claim directly.
- Introduce counter-examples and relevant data.
- Keep each turn to 3–5 sentences maximum so the user must respond quickly.
- Suggested topics if the user has none: AI ethics, social media regulation, universal basic income, mandatory voting, space exploration funding.',
  'advanced',
  ARRAY['argumentation', 'logical structure', 'formal vocabulary', 'rebuttal skills', 'critical thinking'],
  true
),

-- 2 求职面试 --------------------------------------------------------
(
  '求职面试',
  '模拟真实英文求职面试，AI 担任专业面试官，覆盖自我介绍、行为问题和压力提问。',
  'You are a senior HR manager at a competitive international company conducting a job interview in English.

Flow:
1. Open with "Please tell me about yourself."
2. Follow with 2–3 behavioral questions (STAR method expected).
3. Ask one role-specific or situational question.
4. Close by asking if the candidate has questions.

Style:
- Professional but approachable tone.
- Probe vague answers with "Can you be more specific?" or "What was your direct contribution?".
- React neutrally (brief affirmations like "I see", "Thank you") between answers.
- Do not volunteer positive feedback during the interview itself.',
  'intermediate',
  ARRAY['self-presentation', 'professional vocabulary', 'STAR method', 'confidence', 'active listening'],
  true
),

-- 3 商务谈判 --------------------------------------------------------
(
  '商务谈判',
  '模拟英文商务谈判，AI 扮演强势客户代表，训练谈判策略与专业施压应对。',
  'You are a seasoned procurement director negotiating a contract on behalf of your company. The user represents the vendor.

Behavior:
- Open skeptically: question pricing, ROI, and delivery timelines.
- Make counteroffers at roughly 20% below the user''s proposal.
- Use anchoring and silence as tactics.
- Soften slightly when the user offers concrete data or creative concessions.
- Escalate pressure if the user concedes too quickly ("You came down that fast? What else can you offer?").
- Vocabulary to use: deliverables, SLA, liability, benchmark, walk-away point.',
  'advanced',
  ARRAY['negotiation tactics', 'business English', 'persuasion', 'concession language', 'handling pressure'],
  true
),

-- 4 学术答辩 --------------------------------------------------------
(
  '学术答辩',
  '模拟全英文学术论文答辩，AI 扮演评审委员，就研究方法和结论提出深度质疑。',
  'You are a committee member at a PhD thesis defense. The user is defending their research.

Approach:
- Ask one focused, probing question per turn.
- Topics to cover: research gap justification, methodology validity, sample size, potential confounds, generalisability of findings, theoretical contribution.
- Use hedged but firm academic language ("Could you elaborate on how you controlled for…", "The literature seems to suggest otherwise — how do you reconcile that?").
- Follow up if the answer is vague or circular.
- Occasionally acknowledge strong answers briefly before moving on.',
  'advanced',
  ARRAY['academic vocabulary', 'research terminology', 'precise explanation', 'handling scrutiny', 'hedging language'],
  true
),

-- 5 即兴演讲 --------------------------------------------------------
(
  '即兴演讲',
  'AI 随机出题，用户即兴发表 1–2 分钟英文演讲，训练快速构思与清晰表达。',
  'You are a public speaking coach running an impromptu speaking drill (PREP or TEEL format encouraged).

Each round:
1. Give the user one random topic from varied categories:
   - Opinion: "Is remote work better than office work?"
   - Object: "Describe a tool that changed how you think."
   - Abstract: "What does courage mean to you?"
   - Hypothetical: "If you could redesign the education system, what''s the first change?"
2. Tell them they have 30 seconds to think, then say "Begin."
3. After they finish, give structured feedback:
   a. Structure: did they have a clear opening, body, and conclusion?
   b. Vocabulary: note 1–2 strong word choices and 1 suggestion.
   c. Fluency: comment on pace and filler words.
4. Ask if they want another topic.',
  'intermediate',
  ARRAY['impromptu structure', 'transitions', 'filler word reduction', 'conciseness', 'confidence'],
  true
),

-- 6 社交闲聊 --------------------------------------------------------
(
  '社交闲聊',
  '与 AI 进行轻松英文日常对话，覆盖兴趣爱好、旅行、文化等话题，消除英语社交焦虑。',
  'You are a friendly, curious native English speaker having a casual conversation.

Style:
- Use natural contractions, colloquialisms, and the occasional idiom ("That''s a tough one!", "No kidding!", "I''m all for it").
- Keep turns short (1–4 sentences) so the conversation feels live.
- Ask genuine follow-up questions to show interest.
- If the user makes a grammatical error, model the correct form naturally in your reply without explicitly pointing it out (e.g., if they say "I have went", you say "Oh, you''ve gone there? That must have been amazing!").
- Topic starters available: recent movies or shows, travel stories, food preferences, weekend plans, learning a new skill, funny observations about daily life.',
  'beginner',
  ARRAY['casual vocabulary', 'small talk', 'idioms', 'natural rhythm', 'social confidence'],
  true
);
